version: "3"
services:
  qdrant:
    image: qdrant/qdrant
    volumes:
      - ./qdrant_storage:/qdrant/storage
    ports:
      - 6333:6333
    environment:
      - QDRANT__TELEMETRY_DISABLED=True
    networks:
      - base

networks:
  base:
    driver: bridge
